use anyhow::{Context, Result};
use ignore::WalkBuilder;
use std::cmp::Ordering;
use std::path::{Path, PathBuf};

/// Represents a matching file with relevance score and context
#[derive(Debug, Clone)]
pub struct FileMatch {
    pub path: PathBuf,
    pub score: f64,
    pub matching_lines: Vec<MatchedLine>,
}

#[derive(Debug, Clone)]
pub struct MatchedLine {
    pub line_number: usize,
    pub content: String,
    pub context: String,
}

/// FileFinder searches a repository for files and content matching a query.
/// Respects `.gitignore` via the `ignore` crate.
pub struct FileFinder {
    root: PathBuf,
}

impl FileFinder {
    pub fn new(root: &Path) -> Result<Self> {
        Ok(Self {
            root: root.to_path_buf(),
        })
    }

    /// Walk the repo respecting `.gitignore`, returning paths that are source files
    pub fn walk(&self) -> Result<Vec<PathBuf>> {
        let mut files = Vec::new();
        let walker = WalkBuilder::new(&self.root)
            .hidden(false)
            .git_ignore(true)
            .git_global(true)
            .build();

        for entry in walker {
            let entry = entry?;
            if !entry.file_type().is_some_and(|t| t.is_file()) {
                continue;
            }
            let path = entry
                .path()
                .strip_prefix(&self.root)
                .unwrap_or(entry.path());
            if is_source_file(path) {
                files.push(self.root.join(path));
            }
        }

        Ok(files)
    }

    /// Search for a query across all files, returning matches sorted by relevance.
    ///
    /// Propagates walk errors instead of silently returning empty results.
    pub fn search(&self, query: &str, _depth: u8) -> Result<Vec<FileMatch>> {
        let query_lower = query.to_lowercase();
        let terms: Vec<&str> = query_lower.split_whitespace().collect();

        let files = self
            .walk()
            .with_context(|| format!("Failed to walk repository at {}", self.root.display()))?;

        let mut results = Vec::new();

        for full_path in &files {
            let content = match std::fs::read_to_string(full_path) {
                Ok(c) => c,
                Err(_) => continue,
            };

            let file_name = full_path
                .file_name()
                .map(|n| n.to_string_lossy().to_lowercase())
                .unwrap_or_default();

            let rel_path = full_path.strip_prefix(&self.root).unwrap_or(full_path);

            // Score: file name match × 3 + content match count
            let name_score = terms.iter().filter(|t| file_name.contains(*t)).count() as f64 * 3.0;
            let content_lower = content.to_lowercase();
            let content_score = terms.iter().filter(|t| content_lower.contains(*t)).count() as f64;

            let total_score = name_score + content_score;
            if total_score > 0.0 {
                let matching_lines = extract_matching_lines(&content, &terms);
                results.push(FileMatch {
                    path: rel_path.to_path_buf(),
                    score: total_score,
                    matching_lines,
                });
            }
        }

        results.sort_by(|a, b| b.score.partial_cmp(&a.score).unwrap_or(Ordering::Equal));
        Ok(results)
    }
}

/// Check if a file is a source file (not binary/asset/autogenerated)
fn is_source_file(path: &Path) -> bool {
    // Skip common non-source directories
    let path_str = path.to_string_lossy();
    if path_str.contains("node_modules/")
        || path_str.contains(".git/")
        || path_str.contains("target/")
        || path_str.contains("dist/")
        || path_str.contains("build/")
        || path_str.contains("__pycache__/")
        || path_str.contains(".venv/")
        || path_str.contains("vendor/")
    {
        return false;
    }

    matches!(
        path.extension().and_then(|e| e.to_str()),
        Some(
            "rs" | "py"
                | "js"
                | "ts"
                | "tsx"
                | "jsx"
                | "go"
                | "java"
                | "c"
                | "cpp"
                | "h"
                | "hpp"
                | "rb"
                | "php"
                | "swift"
                | "kt"
                | "scala"
                | "cs"
                | "fs"
                | "vue"
                | "svelte"
                | "json"
                | "yaml"
                | "yml"
                | "toml"
                | "md"
                | "css"
                | "scss"
                | "less"
                | "html"
                | "xml"
                | "sql"
                | "graphql"
                | "proto"
                | "prisma"
                | "r"
                | "jl"
                | "ex"
                | "exs"
                | "erl"
                | "hrl"
                | "dart",
        )
    )
}

/// Extract lines from content that match search terms, with ±2 lines context
fn extract_matching_lines(content: &str, terms: &[&str]) -> Vec<MatchedLine> {
    let all_lines: Vec<&str> = content.lines().collect();
    let mut results = Vec::new();

    for (i, line) in all_lines.iter().enumerate() {
        let line_lower = line.to_lowercase();
        if terms.iter().any(|t| line_lower.contains(*t)) {
            let start = i.saturating_sub(2);
            let end = (i + 3).min(all_lines.len());
            let context = all_lines[start..end].join("\n");

            results.push(MatchedLine {
                line_number: i + 1,
                content: line.to_string(),
                context,
            });
        }

        if results.len() >= 50 {
            break;
        }
    }

    results
}
